# 2016.10.21 16:39:01 CST
#Embedded file name: com/fangcloud/httpconnection/HttpErrorMessage.pyc
"""
Created on 2014-12-29

@author: renjun
"""

class HttpErrorMessage:
    ServiceNotFound = 'service_not_found'
    InvalidateLoginInfo = 'invalid_login_info'
    InvalidRequestData = 'invalid_request_data'
    InvalidRefreshToken = 'invalid_refresh_token'
    ResourceNotFound = 'resource_not_found'
    ResourceAccessDenied = 'resource_access_denied'
    ViewerActionDenied = 'viewer_action_denied'
    RegisterDeviceTokenDenied = 'register_device_token_denied'
    RefreshAuthTokenDenied = 'refresh_auth_token_denied'
    BadResource = 'bad_api_resource'
    BadResourceAction = 'bad_api_resource_action'
    BadResourceId = 'bad_resource_id'
    AuthenticationFailed = 'authentication_failed'
    AuthTokenExpired = 'auth_token_expired'
    BadQueryParam = 'bad_api_query_param'
    FailedToProcessRequest = 'failed_to_process_request'
    UserInputValidationError = 'user_input_validation_error'
    ItemNameConflicted = 'item_name_conflicted'
    ActionPermissionDeny = 'action_permission_denied'
    NothingToUpdate = 'nothing_to_update'
    ActionValidationError = 'action_validation_error'
    ShareLinkAliasExists = 'share_link_alias_exists'
    ShareLinkInvalidDueTime = 'share_link_invalid_due_time'
    CommentInvalidMentionedUsers = 'comment_invalid_mentioned_users'
    UserProfilePicUploadFailure = 'user_profile_pic_upload_failure'
    UserProfilePicInvalidType = 'user_profile_pic_invalid_type'
    CommentInvalidVoiceData = 'commend_invalid_voice_data'
    PreviewNotSupported = 'preview_not_supported'
    ReviewNameTooLong = 'review_name_too_long'
    ItemParentMissing = 'item_parent_missing'
    ShareLinkNotFound = 'share_link_not_found'
    ShareLinkExpired = 'share_link_expired'
    ShareLinkInvalidPassword = 'share_link_invalid_password'
    ShareLinkPasswordRequired = 'share_link_password_required'
    ShareLinkAccessDenied = 'share_link_access_denied'
    CollabInvitationAlreadyAnswered = 'collab_invitation_already_answered'
    InvalidShareLinkVerificationCode = 'invalid_share_link_verification_code'
    UserNotFound = 'user_not_found'
    CollabNotFound = 'collab_not_found'
    ItemNotFound = 'item_not_found'
    ItemNotDeleted = 'item_not_deleted'
    SequenceIdLessThanTargetItem = 'sequence_id_less_than_target_item'
    FileNotDeleted = 'file_not_deleted'
    FolderNotDeleted = 'folder_not_deleted'
    ErrorEnterpriseExpired = 'enterprise_expired'
    ExceedEnterpriseSpaceLimit = 'exceed_enterprise_space_limit'
    ExceedCollabUserSpaceLimit = 'exceed_collab_user_space_limit'
    ExceedCollabEnterpriseSpaceLimit = 'exceed_collab_enterprise_space_limit'
    ExceedUserSpaceLimit = 'exceed_user_space_limit'
    FolderNameIsTooLong = 'folder_name_is_too_long'
    FileNameIsTooLong = 'file_name_is_too_long'
    ItemAccessPermissionDenied = 'item_access_permission_denied'
    FileLocked = 'file_locked'
    FileAlreadyLocked = 'file_already_locked'
    UserCannotUnlockFile = 'user_cannot_unlock_file'
    FileLockedFailedWithoutCollab = 'file_locked_failed_without_collab'
    CurrentVersionUnavailable = 'current_version_unavailable'
    UnavailableFileOnServer = 'unavailable_file_on_server'
    DeleteForSyncHasDeletePermission = 'delete_for_sync_has_delete_permission'
    MoveItemOutOfCollarBoundary = 'move_item_out_of_collar_boundary'
    MoveNotAllowedDueToExistenceOfCreator = 'move_not_allowed_due_to_existence_of_creator'
    MoveNotAllowedDueToExistingCollab = 'move_not_allowed_due_to_existing_collab'
    MoveCrossStorage = 'move_cross_storage'
    FolderAlreadyDeleted = 'folder_already_deleted'
    MoveNotAllowedBetweenTwoEnterprise = 'move_not_allowed_between_two_enterprises'
    CrossStorageCopyMoveIsForbidden = 'cross_storage_copy_move_is_forbidden'
    UploadIdExpired = 'url expired!'
    UploadTokenExpired = 'invalid upload token'
    UploadIdMismatch = 'invalid upload id'
    Sha1Mismatch = 'sha1 are inconsistent'
    InvalidUploadParts = 'invalid upload parts'
+++ okay decompyling HttpErrorMessage.pyc 
# decompiled 1 files: 1 okay, 0 failed, 0 verify failed
# 2016.10.21 16:39:01 CST
